/**
 * Migration runner — ТЗ §0, §6 (tardis pattern).
 *
 * Applies the SQL files generated by `drizzle-kit generate` into
 * `backend/drizzle/` on boot, before seedAdmin(). Uses a dedicated single
 * connection (max:1) that is closed when migration finishes, so it can run as a
 * standalone CLI (`bun run db:migrate`) or be imported by the boot sequence.
 */

import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

import { drizzle } from 'drizzle-orm/postgres-js'
import { migrate } from 'drizzle-orm/postgres-js/migrator'
import postgres from 'postgres'

import { logger } from '../lib/logger.js'

// backend/src/db/migrate.ts -> backend/drizzle
const __dirname = dirname(fileURLToPath(import.meta.url))
const MIGRATIONS_FOLDER = resolve(__dirname, '../../drizzle')

export async function runMigrations(): Promise<void> {
  const connectionString = process.env.DATABASE_URL
  if (!connectionString) {
    throw new Error('DATABASE_URL is not set')
  }

  const migrationClient = postgres(connectionString, { max: 1 })
  try {
    const migrationDb = drizzle(migrationClient)
    await migrate(migrationDb, { migrationsFolder: MIGRATIONS_FOLDER })
    logger.info('migrations: applied', { folder: MIGRATIONS_FOLDER })
  } finally {
    await migrationClient.end()
  }
}

// Allow running as a standalone CLI: `bun run src/db/migrate.ts`
if (import.meta.main) {
  runMigrations()
    .then(() => process.exit(0))
    .catch((err: unknown) => {
      logger.error('migrations: failed', { message: (err as Error).message })
      process.exit(1)
    })
}
